# Generated by Django 3.1.4 on 2020-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=70)),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('channel', models.CharField(max_length=40)),
                ('thumbnail', models.CharField(max_length=70)),
                ('sentiment_score', models.FloatField()),
            ],
        ),
    ]
